version: "3.8"

services:
  database:
    image: mongo:4.4
    container_name: tp-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - webnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mydb

  backend:
    build: ./backend
    container_name: tp-backend
    restart: always
    depends_on:
      - database
    environment:
      - MONGO_URL=mongodb://admin:admin@database:27017/mydb?authSource=admin
    ports:
      - "3000:3000"
    networks:
      - webnet

  mongo-express:
    image: mongo-express
    container_name: tp-mongo-express
    restart: always
    depends_on:
      - database
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - webnet

volumes:
  mongo-data:

networks:
  webnet:
